export default {
  NODE_ENV: import.meta.env.VITE_NODE_ENV || import.meta.env.NODE_ENV || 'development',
  API_BASE_URL: import.meta.env.VITE_API_BASE_URL || '',
  APP_BASE_URL: import.meta.env.VITE_APP_BASE_URL || '',
  APP_TITLE: import.meta.env.VITE_APP_TITLE || 'SpiritualPressure',
  APP_VERSION: import.meta.env.VITE_APP_VERSION || '1.0.0',
  DEBUG: import.meta.env.VITE_DEBUG === 'true',
  LOG_LEVEL: import.meta.env.VITE_LOG_LEVEL || 'debug',
  ENABLE_MOCK: import.meta.env.VITE_ENABLE_MOCK === 'true',
  ENABLE_ANALYTICS: import.meta.env.VITE_ENABLE_ANALYTICS === 'true',
  UPLOAD_MAX_SIZE: parseInt(import.meta.env.VITE_UPLOAD_MAX_SIZE) || 10,
  UPLOAD_ALLOWED_TYPES: import.meta.env.VITE_UPLOAD_ALLOWED_TYPES || 'image/jpeg,image/png,image/gif',
  WS_URL: import.meta.env.VITE_WS_URL || 'ws://localhost:8080/ws',
  CDN_BASE_URL: import.meta.env.VITE_CDN_BASE_URL || '',
  WEIXIN_APP_ID: import.meta.env.VITE_WEIXIN_APP_ID || '',
  ALIPAY_APP_ID: import.meta.env.VITE_ALIPAY_APP_ID || '',
  MAP_API_KEY: import.meta.env.VITE_MAP_API_KEY || '',
  MAP_TYPE: import.meta.env.VITE_MAP_TYPE || 'map',
}
